module.exports = [
    "make up",
    "hair care",
    "frangrance",
    "personal care",
    "home & kitchen",
    "office products",
    "office furniture",
    "small appliances",
    "mobile phones",
    "mobile accessories",
    "tablets",
    "computers",
    "printers",
    "data storage",
    "computer accessories",
    "virus software",
    "Swimwear",
    "Dresses",
    "Bottoms",
    "Weddings & Events",
    "Women's Underwear",
    "Shirts",
    "Bottoms",
    "Outerwear & Jackets",
    "Accessories",
    "television and video",
    "Cameras",
    "Speakers",
    "Women's Luggage & Bags",
    "Men's Luggage & Bags",
    "Women's Shoes",
    "Men's Shoes",
    "Hot Categories",
    "For Girls",
    "Remote Control",
    "Baby(0-3years old)",
    "Toys & Hobbies",
    "Swimming",
    "Sneakers",
    "Sportswear",
    "Cycling",
    "Fishing",
    "Sports Equipment",
    "Food Cupboard",
    "household cleaning",
    "beer, wine and spirits",
    "Playstation",
    "Ninetendo",
    "Top Games",
    "xbox",
    "Fine Jewelry",
    "Fashion Jewelry",
    "& Engagement",
    "Jewelry & Watches",
    "Beads & DIY Jewelry",
    "Tools",
    "Indoor Lighting",
    "LED Lighting",
    "Outdoor Lighting"
]